### PR TITLE
 add standardized config interface

### PR DESCRIPTION
**Pull request by helpotters**

### CODE REVIEW

**Comment by helpotters** [comment]
Hey, @helpotters 
Rebase on to main
Sincerely, @helpotters

**Comment by helpotters** [comment]
@ethan-readyset 

I see the issue now. https://github.com/readysettech/readyset-rails/pull/40

I didn't notice that the branch got switched to the `controller-extension` branch and it got merged. When I tried reverting it off main, nothing happened (as it was a different branch), and it got merged with PR #28. 

Not sure what happened here. I may have pulled from `origin/controller-extension` when I was working on PR #28.

**Comment by ethan-readyset** [comment]
Ah, got it. I opened [a draft PR](https://github.com/readysettech/readyset-rails/pull/55#pullrequestreview-1780307910) with the config changes isolated and the comments I had left. Probably easiest for you to just open a new PR based on main with any changes you make from the review and we can go from there?

Hmm AFAIK, merging feature branches into `main` is also a pretty standard setup -- it's the workflow I've always used -- but I'm curious to hear about the `dev` branch setup you mentioned!

Re: your link to stackoverflow, we already use feature branches -- I think the trouble is that we squash and merge our PRs such that they end up being one commit when they are merged. This means that if we have `feature1` based on `main` and `feature2` based on `feature1` and then `feature2` is merged into `feature1`, when `feature1` is merged to main, it will squash the commit from `feature2` into its own commit. So everything ends up in one big commit on `main`. I think we should probably just try to avoid merging PRs until their parent PR has been merged to `main`. Maybe a good way to try to avoid this would be to leave "nested" PRs as draft PRs until their parent has merged?

**Comment by helpotters** [comment]
> I opened https://github.com/readysettech/readyset-rails/pull/55#pullrequestreview-1780307910 with the config changes isolated and the comments I had left.

You are a wizard, Ethan! What sort of git operation :magic_wand:  did you perform to isolate the changes?

> just open a new PR based on main with any changes you make from the review and we can go from there?

Gotcha gotcha. PR based on `main` with the diff from changes :memo: made from the PR #55 review :mag:.

> Hmm AFAIK, merging feature branches into main is also a pretty standard setup -- it's the workflow I've always used -- but I'm curious to hear about the dev branch setup you mentioned!

DMed!

**Pull request closed without merging**
